'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'ar' | 'en' | 'es' | 'it' | 'tr' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.services': 'Soins',
    'nav.gallery': 'Galerie',
    'nav.reviews': 'Avis',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.book': 'Réserver',
    
    // Hero
    'hero.badge': 'EXPÉRIENCE MASSAGE DE LUXE MASCULIN · TÉTOUAN',
    'hero.title1': 'L\'art suprême de la ',
    'hero.titleItalic': 'relaxation',
    'hero.title2': ' pour hommes',
    'hero.desc1': 'Libérez votre esprit et revitalisez votre corps au cœur de Tétouan. ',
    'hero.descBold': 'SPA RELAX ISTANBUL',
    'hero.desc2': ' vous offre des massages d\'exception dans un cadre privé, élégant et exclusivement masculin.',
    'hero.descItalic': ' Massage 100% professionnel, thérapeutique et anti-stress.',
    'hero.trust.masseur': 'Masseurs Experts',
    'hero.trust.frame': 'Cadre Privé Discret',
    'hero.trust.hygiene': 'Hygiène Stricte',
    'hero.btn.wa': 'RÉSERVER SUR WHATSAPP',
    'hero.btn.services': 'NOS SERVICES',

    // Benefits
    'benefits.label': 'Pourquoi Choisir Notre Centre',
    'benefits.title': 'L\'excellence du bien-être masculin',
    'benefits.desc': 'Nous redéfinissons les standards du massage pour hommes à Tétouan grâce à des thérapeutes qualifiés et des soins haut de gamme.',
    'benefits.b1.title': 'Hygiène Absolue',
    'benefits.b1.desc': 'Cabines nettoyées et désinfectées après chaque passage, draps et serviettes à usage unique.',
    'benefits.b2.title': 'Confidentialité Totale',
    'benefits.b2.desc': 'Espace chaleureux, discret et respectueux de votre intimité. Entrée et sortie sécurisées.',
    'benefits.b3.title': 'Thérapeutes Certifiés',
    'benefits.b3.desc': 'Une équipe professionnelle maîtrisant les techniques de relaxation orientales et occidentales.',
    'benefits.b4.title': 'Huiles Bio Premium',
    'benefits.b4.desc': 'Utilisation exclusive d\'huiles essentielles précieuses, bio et adaptées à votre type de peau.',

    // Services
    'services.label': 'Nos Rituels de Soins',
    'services.title': 'Massages d\'Exception & Thérapies',
    'services.desc': 'Chaque massage est réalisé par un expert certifié, utilisant des huiles d\'aromathérapie et s\'adaptant précisément à vos tensions physiques.',
    'services.rec': 'Recommandé',
    'services.min': 'Min',
    'services.btn': 'Réserver sur WhatsApp',
    'services.s1.title': 'Massage Relaxant Traditionnel',
    'services.s1.desc': 'Un massage fluide et enveloppant sur l\'ensemble du corps. Idéal pour éliminer la fatigue quotidienne, relâcher les tensions musculaires et restaurer une harmonie totale.',
    'services.s2.title': 'Massage Deep Tissue (Anti-Stress)',
    'services.s2.desc': 'Un massage profond ciblant les fascias et les muscles en profondeur. Recommandé pour les sportifs, les professionnels actifs et les personnes souffrant de tensions au dos.',
    'services.s3.title': 'Massage Oriental aux Pierres Chaudes',
    'services.s3.desc': 'L\'alliance parfaite de la chaleur thérapeutique de pierres volcaniques et de pressions relaxantes. Favorise une profonde détente musculaire et améliore la circulation.',
    'services.s4.title': 'Rituel VIP - SPA RELAX ISTANBUL',
    'services.s4.desc': 'Notre expérience ultime de relaxation. Un massage sur-mesure combinant aromathérapie aux huiles précieuses, massage crânien apaisant et réflexologie plantaire complète.',

    // Gallery
    'gallery.label': 'Visite Guidée',
    'gallery.title': 'Galerie de Notre Centre',
    'gallery.desc': 'Plongez dans l\'atmosphère raffinée de notre spa à Tétouan. Un décor soigné, des lumières tamisées et une hygiène rigoureuse pour votre bien-être total.',
    'gallery.c1': 'Espace Relax',
    'gallery.c2': 'Ingrédients & Soins',
    'gallery.c3': 'Ambiance',
    'gallery.c4': 'Soin Homme',
    'gallery.c5': 'Cadre Privé',
    'gallery.c6': 'Espace Client',
    'gallery.t1': 'Cabine Privée Premium',
    'gallery.t2': 'Détente Totale',
    'gallery.t3': 'Cadre Thérapeutique',
    'gallery.t4': 'Pédicure & Soin des Pieds',
    'gallery.t5': 'Ambiance Feutrée',
    'gallery.t6': 'Accueil VIP',
    'gallery.cta.title': 'Prêt pour un moment de relaxation absolue ?',
    'gallery.cta.desc': 'Réservez dès maintenant votre créneau horaire sur WhatsApp. Accueil rapide et discret.',
    'gallery.cta.btn': '📲 Réserver ma séance',

    // Testimonials
    'reviews.label': 'Avis de Nos Clients',
    'reviews.title': 'Ce que nos clients disent de nous',
    'reviews.desc': 'La satisfaction et la discrétion de nos clients sont nos plus grandes priorités. Découvrez leurs retours d\'expérience après leur passage chez SPA RELAX ISTANBUL.',
    'reviews.r1.name': 'Youssef El Amrani',
    'reviews.r1.role': 'Chef d\'entreprise, Tétouan',
    'reviews.r1.quote': 'Franchement, le meilleur centre de massage pour hommes à Tétouan. Le cadre est luxueux, propre et surtout très discret. Le massage Deep Tissue m\'a complètement libéré de mes douleurs musculaires.',
    'reviews.r2.name': 'Amine B.',
    'reviews.r2.role': 'Professionnel Libéral, Tanger',
    'reviews.r2.quote': 'Service 5 étoiles ! L\'accueil est irréprochable et respectueux. Tout est fait pour qu\'on se sente à l\'aise. L\'hygiène des cabines est impeccable. C\'est mon adresse favorite dans la région.',
    'reviews.r3.name': 'Rachid Tetouani',
    'reviews.r3.role': 'Client Régulier, Tétouan',
    'reviews.r3.quote': 'Un vrai massage professionnel thérapeutique ! Rien à voir avec d\'autres endroits basiques. Les huiles utilisées sont de très haute qualité. Une adresse à recommander sans hésitation.',

    // FAQ
    'faq.label': 'Foire Aux Questions',
    'faq.title': 'Des questions ? Nous avons les réponses',
    'faq.desc': 'Retrouvez toutes les réponses aux questions les plus fréquentes sur nos massages, notre politique de réservation et notre centre à Tétouan.',
    'faq.q1': 'Les massages sont-ils mixtes ou réservés aux hommes ?',
    'faq.a1': 'SPA RELAX ISTANBUL est un espace exclusivement masculin (men-only). Les soins sont prodigués dans un cadre privatisé pour assurer le plus haut niveau de confort, de respect et de relaxation aux hommes.',
    'faq.q2': 'Proposez-vous des services de hammam ou de gommage ?',
    'faq.a2': 'Non, notre centre est exclusivement spécialisé dans les soins de massage professionnels et thérapeutiques de haute qualité. Nous ne proposons pas de service de hammam traditionnel.',
    'faq.q3': 'Faut-il obligatoirement réserver à l\'avance ?',
    'faq.a3': 'Oui, afin de vous garantir une cabine privée et une disponibilité immédiate sans attente, toutes nos séances de massage se font uniquement sur réservation préalable.',
    'faq.q4': 'Quels types d\'huiles de massage utilisez-vous ?',
    'faq.a4': 'Nous utilisons exclusivement des huiles d\'amande douce, des huiles de coco biologiques et des huiles essentielles précieuses sélectionnées pour leurs vertus apaisantes, hydratantes et réparatrices.',
    'faq.q5': 'Où se situe exactement le spa à Tétouan ?',
    'faq.a5': 'Notre centre de bien-être est situé Avenue Kaboul, Tiknia 93030, à Tétouan. Un emplacement calme, élégant et facile d\'accès avec possibilité de stationnement à proximité.',

    // Location
    'contact.label': 'Où Nous Trouver',
    'contact.title': 'Notre Centre à Tétouan',
    'contact.desc': 'Idéalement situé dans un quartier tranquille et facile d\'accès à Tétouan. Venez vous ressourcer dans notre espace dédié au bien-être masculin.',
    'contact.info': 'INFORMATIONS DE CONTACT',
    'contact.address.label': 'Adresse',
    'contact.address.val': 'SPA RELAX ISTANBUL, Avenue Kaboul, Tiknia 93030, Tétouan, Maroc',
    'contact.phone.label': 'WhatsApp & Téléphone',
    'contact.phone.val': '+212779403213',
    'contact.hours.label': 'Horaires d\'Ouverture',
    'contact.hours.val': 'Tous les jours : de 10:30 à 23:30',
    'contact.hours.note': '* Uniquement sur rendez-vous ou réservation préalable.',
    'contact.btn.wa': '📲 Réserver sur WhatsApp',
    'contact.btn.maps': '🗺 Itinéraire Google Maps',

    // Footer
    'footer.slogan': 'ISTANBUL · TETOUAN',
    'footer.desc': 'Centre de massage de luxe pour hommes à Tétouan. Un havre exclusif où la relaxation rencontre le raffinement ottoman et l\'exigence professionnelle.',
    'footer.spec.title': 'Nos Spécialités',
    'footer.spec.s1': 'Massage Relaxant Professionnel',
    'footer.spec.s2': 'Massage Deep Tissue Anti-stress',
    'footer.spec.s3': 'Thérapie aux Pierres Chaudes',
    'footer.spec.s4': 'Massage Crânien & Réflexologie',
    'footer.spec.s5': 'Aromathérapie aux Huiles Bio',
    'footer.spec.s6': 'Rituels Massage VIP Homme',
    'footer.contact.title': 'Contact Rapide',
    'footer.btn.live': '📲 WhatsApp Live Chat',
    'footer.copy': 'Tous droits réservés. Massages exclusivement professionnels & masculins.',
    'footer.legal': 'Mentions Légales',
    'footer.privacy': 'Politique de Confidentialité',

    // Chatbot
    'chat.notify': 'Bonjour! Une question ?',
    'chat.status': 'En ligne maintenant',
    'chat.greet1': 'Marhaban! Bienvenue chez SPA RELAX ISTANBUL à Tétouan. 🇲🇦🇹🇷',
    'chat.greet2': 'Je suis Youssef, votre conseiller bien-être. Comment puis-je vous aider aujourd\'hui ?',
    'chat.hours': 'Responsable Spa · 10:30 - 23:30',
    'chat.opt1': '💆‍♂️ Réserver une séance de massage',
    'chat.opt2': '💰 Connaître les tarifs et offres',
    'chat.opt3': '📍 Itinéraire et adresse du centre',
    'chat.opt4': '🤔 Question sur les types de massage',
    'chat.placeholder': 'Écrivez votre message...',
  },
  ar: {
    // Navbar
    'nav.home': 'الرئيسية',
    'nav.services': 'العلاجات',
    'nav.gallery': 'المعرض',
    'nav.reviews': 'الآراء',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.contact': 'اتصل بنا',
    'nav.book': 'حجز موعد',

    // Hero
    'hero.badge': 'تجربة مساج فاخرة للرجال · تطوان',
    'hero.title1': 'الفن الأسمى ',
    'hero.titleItalic': 'للاسترخاء',
    'hero.title2': ' للرجال',
    'hero.desc1': 'حرر عقلك واستعد نشاط جسمك في قلب تطوان. يقدم لك ',
    'hero.descBold': 'SPA RELAX ISTANBUL',
    'hero.desc2': ' جلسات تدليك استثنائية في إطار خاص، أنيق ومخصص حصرياً للرجال.',
    'hero.descItalic': ' مساج احترافي 100%، علاجي ومضاد للتوتر.',
    'hero.trust.masseur': 'خبراء مساج محترفين',
    'hero.trust.frame': 'إطار خاص وسري',
    'hero.trust.hygiene': 'نظافة صارمة ومضمونة',
    'hero.btn.wa': 'احجز الآن عبر الواتساب',
    'hero.btn.services': 'خدماتنا المميزة',

    // Benefits
    'benefits.label': 'لماذا تختار مركزنا',
    'benefits.title': 'التميز في الرفاهية الذكورية',
    'benefits.desc': 'نعيد تحديد معايير المساج للرجال في تطوان بفضل معالجين مؤهلين وعلاجات راقية.',
    'benefits.b1.title': 'نظافة مطلقة',
    'benefits.b1.desc': 'يتم تنظيف وتطهير الكبائن بعد كل عميل، مع استخدام ملاءات ومناشف ذات استخدام واحد.',
    'benefits.b2.title': 'خصوصية تامة',
    'benefits.b2.desc': 'مساحة دافئة وسرية تحترم خصوصيتك بالكامل مع مداخل ومخارج آمنة.',
    'benefits.b3.title': 'معالجون معتمدون',
    'benefits.b3.desc': 'طاقم محترف يتقن أحدث تقنيات الاسترخاء والتدليك الشرقية والغربية.',
    'benefits.b4.title': 'زيوت عضوية ممتازة',
    'benefits.b4.desc': 'استخدام حصري للزيوت العطرية العضوية الثمينة والمناسبة لنوع بشرتك.',

    // Services
    'services.label': 'طقوس العلاج لدينا',
    'services.title': 'حصص تدليك استثنائية وعلاجات',
    'services.desc': 'تتم كل حصة تدليك على يد خبير معتمد، باستخدام زيوت عطرية مخصصة لتلبية احتياجات جسمك وتخفيف التوتر.',
    'services.rec': 'موصى به',
    'services.min': 'دقيقة',
    'services.btn': 'احجز عبر الواتساب',
    'services.s1.title': 'المساج الاسترخائي التقليدي',
    'services.s1.desc': 'تدليك سلس وشامل للجسم. مثالي للتخلص من التعب اليومي، وإرخاء العضلات واستعادة التوازن التام.',
    'services.s2.title': 'مساج الأنسجة العميقة (مضاد للتوتر)',
    'services.s2.desc': 'تدليك عميق يستهدف العضلات والأنسجة العميقة. يوصى به للرياضيين وأصحاب المهن النشطة للتخلص من آلام الظهر والكتفين.',
    'services.s3.title': 'المساج الشرقي بالأحجار الدافئة',
    'services.s3.desc': 'مزيج مثالي بين الحرارة العلاجية للأحجار البركانية وضغط الاسترخاء. يساعد على الاسترخاء العميق وتحسين الدورة الدموية.',
    'services.s4.title': 'الطقس الفخم VIP - سبا ريلاكس إسطنبول',
    'services.s4.desc': 'تجربتنا الأرقى للاسترخاء. تدليك مخصص يجمع بين الزيوت العطرية الفاخرة، وتدليك الرأس المهدئ وعلم المنعكسات للقدمين.',

    // Gallery
    'gallery.label': 'جولة مصورة',
    'gallery.title': 'معرض الصور لمركزنا',
    'gallery.desc': 'انغمس في الأجواء الراقية لمركزنا في تطوان. ديكور أنيق، إضاءة هادئة ونظافة صارمة لضمان راحتك التامة.',
    'gallery.c1': 'مساحة الاسترخاء',
    'gallery.c2': 'المكونات والعلاجات',
    'gallery.c3': 'الأجواء الهادئة',
    'gallery.c4': 'العناية بالرجل',
    'gallery.c5': 'إطار خاص',
    'gallery.c6': 'مساحة الاستقبال',
    'gallery.t1': 'كابينة خاصة فاخرة',
    'gallery.t2': 'استرخاء تام',
    'gallery.t3': 'أجواء علاجية هادئة',
    'gallery.t4': 'الباديكير والعناية بالقدمين',
    'gallery.t5': 'إضاءة دافئة',
    'gallery.t6': 'استقبال VIP الفخم',
    'gallery.cta.title': 'هل أنت مستعد للحظة استرخاء مطلق؟',
    'gallery.cta.desc': 'احجز موعدك الآن بسهولة عبر الواتساب. استقبال سريع وبسرية تامة.',
    'gallery.cta.btn': '📲 احجز حصتك الآن',

    // Testimonials
    'reviews.label': 'آراء عملائنا',
    'reviews.title': 'ماذا يقول عملائنا عنا',
    'reviews.desc': 'رضا وسرية عملائنا هما أولويتنا القصوى. اكتشف تجاربهم بعد زيارتهم لمركز سبا ريلاكس إسطنبول.',
    'reviews.r1.name': 'يوسف العمراني',
    'reviews.r1.role': 'رجل أعمال، تطوان',
    'reviews.r1.quote': 'بصراحة، أفضل مركز مساج للرجال في تطوان. المكان فاخر ونظيف للغاية والأهم من ذلك أنه سري جداً. مساج الأنسجة العميقة خلصني تماماً من آلام الظهر.',
    'reviews.r2.name': 'أمين ب.',
    'reviews.r2.role': 'مهني حر، طنجة',
    'reviews.r2.quote': 'خدمة 5 نجوم! الاستقبال راقٍ ومحترم جداً. كل شيء مهيأ لتشعر بالراحة. نظافة الكبائن لا غبار عليها. إنه عنواني المفضل دائماً.',
    'reviews.r3.name': 'رشيد التطواني',
    'reviews.r3.role': 'زبون دائم، تطوان',
    'reviews.r3.quote': 'جلسة مساج علاجي احترافي حقيقي! يختلف تماماً عن الأماكن العادية الأخرى. الزيوت المستخدمة عالية الجودة. أنصح به بشدة وبدون تردد.',

    // FAQ
    'faq.label': 'الأسئلة الشائعة',
    'faq.title': 'هل لديك أسئلة؟ لدينا الإجابات',
    'faq.desc': 'اعثر على جميع الإجابات للأسئلة الشائعة حول خدمات التدليك، سياسة الحجز وموقع مركزنا في تطوان.',
    'faq.q1': 'هل خدمات التدليك مختلطة أم للرجال فقط؟',
    'faq.a1': 'مركز سبا ريلاكس إسطنبول مخصص حصرياً للرجال (Men-only). تُقدم الخدمات في إطار خاص لضمان أعلى مستويات الراحة والاحترام والاسترخاء للرجال.',
    'faq.q2': 'هل تقدمون خدمات الحمام المغربي أو التقشير؟',
    'faq.a2': 'لا، مركزنا متخصص حصرياً في خدمات المساج والتدليك العلاجي الاحترافي عالي الجودة. لا نقدم خدمات الحمام التقليدي.',
    'faq.q3': 'هل الحجز المسبق إجباري؟',
    'faq.a3': 'نعم، لضمان توفير كابينة خاصة لك وبدون أي انتظار، جميع جلسات المساج لدينا تتم حصرياً بناءً على حجز مسبق عبر الهاتف أو الواتساب.',
    'faq.q4': 'ما هي أنواع الزيوت التي تستخدمونها؟',
    'faq.a4': 'نستخدم حصرياً زيوت اللوز الحلو الطبيعية، وزيت جوز الهند العضوي، ومجموعة من الزيوت العطرية الثمينة المهدئة والمغذية للبشرة.',
    'faq.q5': 'أين يقع المركز بالضبط في تطوان؟',
    'faq.a5': 'يقع مركزنا الاسترخائي في شارع كابول، التكنية 93030، تطوان. موقع هادئ، أنيق وسهل الوصول إليه مع توفر مواقف للسيارات في الجوار.',

    // Location
    'contact.label': 'أين تجدنا',
    'contact.title': 'مركزنا في تطوان',
    'contact.desc': 'يقع في منطقة هادئة وسهلة الوصول في تطوان. تفضل بزيارتنا لتجديد نشاطك في مكان مخصص لراحة الرجل.',
    'contact.info': 'معلومات الاتصال',
    'contact.address.label': 'العنوان',
    'contact.address.val': 'SPA RELAX ISTANBUL، شارع كابول، التكنية 93030، تطوان، المغرب',
    'contact.phone.label': 'الواتساب والهاتف',
    'contact.phone.val': '\u202D+212 779-403213\u202C',
    'contact.hours.label': 'أوقات العمل',
    'contact.hours.val': 'يومياً من الساعة 10:30 صباحاً حتى 11:30 مساءً',
    'contact.hours.note': '* الحجز المسبق مطلوب دائماً.',
    'contact.btn.wa': '📲 احجز الآن عبر الواتساب',
    'contact.btn.maps': '🗺 مسار جوجل مابس',

    // Footer
    'footer.slogan': 'إسطنبول · تطوان',
    'footer.desc': 'مركز مساج فاخر للرجال في تطوان. ملاذ حصري حيث تلتقي متعة الاسترخاء باللمسة العثمانية الراقية والخبرة العلاجية المحترفة.',
    'footer.spec.title': 'تخصصاتنا',
    'footer.spec.s1': 'مساج استرخائي احترافي',
    'footer.spec.s2': 'مساج الأنسجة العميقة المضاد للتوتر',
    'footer.spec.s3': 'العلاج الفاخر بالأحجار الدافئة',
    'footer.spec.s4': 'مساج الرأس وعلم المنعكسات',
    'footer.spec.s5': 'العلاج بالزيوت العطرية العضوية',
    'footer.spec.s6': 'طقوس مساج VIP الفخمة للرجال',
    'footer.contact.title': 'اتصال سريع',
    'footer.btn.live': '📲 دردشة واتساب مباشرة',
    'footer.copy': 'جميع الحقوق محفوظة. جلسات تدليك احترافية ومخصصة للرجال فقط.',
    'footer.legal': 'الشروط القانونية',
    'footer.privacy': 'سياسة الخصوصية',

    // Chatbot
    'chat.notify': 'مرحباً! هل لديك سؤال ؟',
    'chat.status': 'متصل الآن',
    'chat.greet1': 'مرحباً بك في SPA RELAX ISTANBUL في تطوان. 🇲🇦🇹🇷',
    'chat.greet2': 'أنا يوسف، مستشارك الخاص للرفاهية. كيف يمكنني مساعدتك اليوم؟',
    'chat.hours': 'مسؤول السبا · 10:30 - 23:30',
    'chat.opt1': '💆‍♂️ حجز موعد تدليك',
    'chat.opt2': '💰 الاستفسار عن الأسعار والعروض',
    'chat.opt3': '📍 موقع المركز وشارع الوصول',
    'chat.opt4': '🤔 سؤال عن أنواع المساج المتوفرة',
    'chat.placeholder': 'اكتب رسالتك هنا...',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.gallery': 'Gallery',
    'nav.reviews': 'Reviews',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.book': 'Book Now',

    // Hero
    'hero.badge': 'PREMIUM LUXURY MEN-ONLY MASSAGE · TETOUAN',
    'hero.title1': 'The ultimate art of ',
    'hero.titleItalic': 'relaxation',
    'hero.title2': ' for men',
    'hero.desc1': 'Release your mind and revitalize your body in the heart of Tetouan. ',
    'hero.descBold': 'SPA RELAX ISTANBUL',
    'hero.desc2': ' offers exceptional massages in a private, elegant, and exclusively masculine setting.',
    'hero.descItalic': ' 100% professional, therapeutic, and anti-stress massage.',
    'hero.trust.masseur': 'Expert Masseurs',
    'hero.trust.frame': 'Discreet Private Setting',
    'hero.trust.hygiene': 'Strict Hygiene Standards',
    'hero.btn.wa': 'BOOK VIA WHATSAPP',
    'hero.btn.services': 'OUR SERVICES',

    // Benefits
    'benefits.label': 'Why Choose Us',
    'benefits.title': 'Excellence in Men\'s Wellness',
    'benefits.desc': 'We redefine the standards of men\'s massage in Tetouan thanks to our highly certified therapists and high-end treatments.',
    'benefits.b1.title': 'Absolute Hygiene',
    'benefits.b1.desc': 'Cabins thoroughly cleaned and sanitized after each client; single-use sheets and towels.',
    'benefits.b2.title': 'Total Discretion',
    'benefits.b2.desc': 'Warm, highly discreet environment that fully respects your privacy. Secure entry and exit.',
    'benefits.b3.title': 'Certified Therapists',
    'benefits.b3.desc': 'A professional team mastering the finest Eastern and Western relaxation techniques.',
    'benefits.b4.title': 'Organic Bio Oils',
    'benefits.b4.desc': 'Exclusive use of organic, premium essential oils adjusted to your skin type.',

    // Services
    'services.label': 'Our Care Rituals',
    'services.title': 'Exceptional Massages & Therapies',
    'services.desc': 'Each massage is performed by a certified expert, using custom aromatherapy oils adapted to your physical tensions.',
    'services.rec': 'Recommended',
    'services.min': 'Min',
    'services.btn': 'Book on WhatsApp',
    'services.s1.title': 'Traditional Relaxing Massage',
    'services.s1.desc': 'A fluid and wrapping full-body massage. Ideal for eliminating daily fatigue, releasing muscle tension, and restoring total harmony.',
    'services.s2.title': 'Deep Tissue Massage (Anti-Stress)',
    'services.s2.desc': 'A deep massage targeting deep muscle layers and fascia. Recommended for athletes, active professionals, and back tension.',
    'services.s3.title': 'Oriental Hot Stone Massage',
    'services.s3.desc': 'The perfect blend of hot volcanic stones and relaxing pressure. Promotes deep muscle relaxation and improves circulation.',
    'services.s4.title': 'VIP Ritual - SPA RELAX ISTANBUL',
    'services.s4.desc': 'Our ultimate relaxation experience. A tailor-made massage combining organic essential oils, calming head massage, and reflexology.',

    // Gallery
    'gallery.label': 'Guided Tour',
    'gallery.title': 'Gallery of Our Center',
    'gallery.desc': 'Immerse yourself in the refined atmosphere of our spa in Tetouan. Tailored decoration, soft lights, and strict hygiene.',
    'gallery.c1': 'Relax Space',
    'gallery.c2': 'Ingredients & Care',
    'gallery.c3': 'Ambiance',
    'gallery.c4': 'Men\'s Grooming',
    'gallery.c5': 'Private Setting',
    'gallery.c6': 'Reception',
    'gallery.t1': 'Premium Private Cabin',
    'gallery.t2': 'Total Relaxation',
    'gallery.t3': 'Therapeutic Setting',
    'gallery.t4': 'Pedicure & Foot Care',
    'gallery.t5': 'Dimmed Cozy Atmosphere',
    'gallery.t6': 'VIP Welcome Lobby',
    'gallery.cta.title': 'Ready for a moment of absolute relaxation?',
    'gallery.cta.desc': 'Book your slot now on WhatsApp. Fast and fully discreet scheduling.',
    'gallery.cta.btn': '📲 Book My Session',

    // Testimonials
    'reviews.label': 'Customer Reviews',
    'reviews.title': 'What our clients say about us',
    'reviews.desc': 'Our clients\' satisfaction and discretion are our highest priorities. Discover their experience at SPA RELAX ISTANBUL.',
    'reviews.r1.name': 'Youssef El Amrani',
    'reviews.r1.role': 'Business Owner, Tetouan',
    'reviews.r1.quote': 'Honestly, the best massage center for men in Tetouan. The place is luxurious, clean, and extremely discreet. The Deep Tissue massage completely freed me from muscle pain.',
    'reviews.r2.name': 'Amine B.',
    'reviews.r2.role': 'Freelance Professional, Tangier',
    'reviews.r2.quote': '5-star service! The welcome is respectful and professional. Everything is designed to make you feel comfortable. The hygiene is spotless.',
    'reviews.r3.name': 'Rachid Tetouani',
    'reviews.r3.role': 'Regular Client, Tetouan',
    'reviews.r3.quote': 'A real professional therapeutic massage! Nothing like other basic places. The oils used are of very high quality. Highly recommended.',

    // FAQ
    'faq.label': 'Frequently Asked Questions',
    'faq.title': 'Have questions? We have the answers',
    'faq.desc': 'Find all the answers to the most common questions about our massages, booking policies, and center in Tetouan.',
    'faq.q1': 'Are the massages mixed or only for men?',
    'faq.a1': 'SPA RELAX ISTANBUL is an exclusively male environment (men-only). Massages are given in a fully private setting to ensure the highest comfort, respect, and relaxation.',
    'faq.q2': 'Do you offer hammam or scrubbing services?',
    'faq.a2': 'No, our center is exclusively specialized in professional, high-quality therapeutic massages. We do not provide traditional hammam services.',
    'faq.q3': 'Is booking in advance mandatory?',
    'faq.a3': 'Yes, to guarantee your private cabin and immediate availability without wait times, all massage sessions are strictly by prior reservation.',
    'faq.q4': 'What kind of massage oils do you use?',
    'faq.a4': 'We exclusively use sweet almond oils, organic coconut oils, and premium organic essential oils selected for their soothing and restorative properties.',
    'faq.q5': 'Where is the spa located in Tetouan?',
    'faq.a5': 'Our wellness center is located on Kabul Avenue, Tiknia 93030, Tetouan. A calm, elegant, and highly accessible spot with nearby parking options.',

    // Location
    'contact.label': 'Where to Find Us',
    'contact.title': 'Our Center in Tetouan',
    'contact.desc': 'Ideally located in a quiet and highly accessible neighborhood in Tetouan. Come recharge in our men-only wellness space.',
    'contact.info': 'CONTACT INFORMATION',
    'contact.address.label': 'Address',
    'contact.address.val': 'SPA RELAX ISTANBUL, Kabul Avenue, Tiknia 93030, Tetouan, Morocco',
    'contact.phone.label': 'WhatsApp & Phone',
    'contact.phone.val': '+212779403213',
    'contact.hours.label': 'Opening Hours',
    'contact.hours.val': 'Every day: from 10:30 to 23:30',
    'contact.hours.note': '* Strictly by prior appointment or reservation.',
    'contact.btn.wa': '📲 Book on WhatsApp',
    'contact.btn.maps': '🗺 Google Maps Directions',

    // Footer
    'footer.slogan': 'ISTANBUL · TETOUAN',
    'footer.desc': 'Luxury massage center for men in Tetouan. An exclusive haven where absolute relaxation meets Ottoman refinement and therapeutic excellence.',
    'footer.spec.title': 'Our Specialties',
    'footer.spec.s1': 'Professional Relaxing Massage',
    'footer.spec.s2': 'Anti-Stress Deep Tissue Massage',
    'footer.spec.s3': 'Volcanic Hot Stone Therapy',
    'footer.spec.s4': 'Head Massage & Reflexology',
    'footer.spec.s5': 'Bio Organic Aromatherapy',
    'footer.spec.s6': 'VIP Custom Men\'s Rituals',
    'footer.contact.title': 'Quick Contact',
    'footer.btn.live': '📲 WhatsApp Live Chat',
    'footer.copy': 'All rights reserved. Strictly professional & men-only wellness treatments.',
    'footer.legal': 'Legal Notice',
    'footer.privacy': 'Privacy Policy',

    // Chatbot
    'chat.notify': 'Hello! Any questions?',
    'chat.status': 'Online now',
    'chat.greet1': 'Marhaban! Welcome to SPA RELAX ISTANBUL in Tetouan. 🇲🇦🇹🇷',
    'chat.greet2': 'I am Youssef, your wellness advisor. How can I help you today?',
    'chat.hours': 'Spa Manager · 10:30 - 23:30',
    'chat.opt1': '💆‍♂️ Book a massage session',
    'chat.opt2': '💰 Ask about prices and offers',
    'chat.opt3': '📍 Find directions to the center',
    'chat.opt4': '🤔 Ask about types of massages',
    'chat.placeholder': 'Type your message...',
  },
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.services': 'Masajes',
    'nav.gallery': 'Galería',
    'nav.reviews': 'Opiniones',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacto',
    'nav.book': 'Reservar',

    // Hero
    'hero.badge': 'MASAJE MASCULINO DE LUJO PREMIUM · TETUÁN',
    'hero.title1': 'El arte supremo de la ',
    'hero.titleItalic': 'relajación',
    'hero.title2': ' para hombres',
    'hero.desc1': 'Libera tu mente y revitaliza tu cuerpo en el corazón de Tetuán. ',
    'hero.descBold': 'SPA RELAX ISTANBUL',
    'hero.desc2': ' te ofrece masajes excepcionales en un entorno privado, elegante y exclusivamente masculino.',
    'hero.descItalic': ' Masaje 100% profesional, terapéutico y antiestrés.',
    'hero.trust.masseur': 'Masajistas Expertos',
    'hero.trust.frame': 'Entorno Privado y Discreto',
    'hero.trust.hygiene': 'Higiene Rigurosa',
    'hero.btn.wa': 'RESERVAR POR WHATSAPP',
    'hero.btn.services': 'NUESTROS SERVICIOS',

    // Benefits
    'benefits.label': 'Por Qué Elegirnos',
    'benefits.title': 'La excelencia en bienestar masculino',
    'benefits.desc': 'Redefinimos los estándares del masaje masculino en Tetuán gracias a terapeutas altamente certificados y tratamientos de alta gama.',
    'benefits.b1.title': 'Higiene Absoluta',
    'benefits.b1.desc': 'Cabinas completamente limpiadas y desinfectadas después de cada cliente; sábanas y toallas de un solo uso.',
    'benefits.b2.title': 'Discreción Total',
    'benefits.b2.desc': 'Ambiente cálido y altamente discreto que respeta plenamente su privacidad. Entrada y salida seguras.',
    'benefits.b3.title': 'Terapeutas Certificados',
    'benefits.b3.desc': 'Un equipo profesional que domina las mejores técnicas de relajación orientales y occidentales.',
    'benefits.b4.title': 'Aceites Orgánicos Premium',
    'benefits.b4.desc': 'Uso exclusivo de aceites esenciales orgánicos premium adaptados a su tipo de piel.',

    // Services
    'services.label': 'Nuestros Rituales de Cuidado',
    'services.title': 'Masajes Excepcionales y Terapias',
    'services.desc': 'Cada masaje es realizado por un experto certificado, utilizando aceites de aromaterapia adaptados a sus tensiones físicas.',
    'services.rec': 'Recomendado',
    'services.min': 'Min',
    'services.btn': 'Reservar por WhatsApp',
    'services.s1.title': 'Masaje Relajante Tradicional',
    'services.s1.desc': 'Un masaje fluido y envolvente por todo el cuerpo. Ideal para eliminar la fatiga diaria, liberar tensiones musculares y restaurar la armonía total.',
    'services.s2.title': 'Masaje de Tejido Profundo (Antiestrés)',
    'services.s2.desc': 'Un masaje profundo dirigido a las capas musculares y la fascia. Recomendado para deportistas, profesionales activos y tensiones de espalda.',
    'services.s3.title': 'Masaje Oriental con Piedras Calientes',
    'services.s3.desc': 'La combinación perfecta de piedras volcánicas calientes y presión relajante. Promueve una relajación muscular profunda y mejora la circulación.',
    'services.s4.title': 'Ritual VIP - SPA RELAX ISTANBUL',
    'services.s4.desc': 'Nuestra experiencia de relajación definitiva. Un masaje a medida que combina aceites esenciales orgánicos, masaje de cabeza calmante y reflexología.',

    // Gallery
    'gallery.label': 'Visita Guiada',
    'gallery.title': 'Galería de Nuestro Centro',
    'gallery.desc': 'Sumérjase en la atmósfera refinada de nuestro spa en Tetuán. Decoración cuidada, luces suaves e higiene estricta.',
    'gallery.c1': 'Espacio Relax',
    'gallery.c2': 'Ingredientes y Cuidado',
    'gallery.c3': 'Ambiente',
    'gallery.c4': 'Cuidado Masculino',
    'gallery.c5': 'Entorno Privado',
    'gallery.c6': 'Recepción',
    'gallery.t1': 'Cabina Privada Premium',
    'gallery.t2': 'Relajación Total',
    'gallery.t3': 'Entorno Terapéutico',
    'gallery.t4': 'Pedicura y Cuidado de Pies',
    'gallery.t5': 'Ambiente Cálido y Tenue',
    'gallery.t6': 'Recepción VIP',
    'gallery.cta.title': '¿Listo para un momento de relajación absoluta?',
    'gallery.cta.desc': 'Reserve su cita ahora en WhatsApp. Programación rápida y totalmente discreta.',
    'gallery.cta.btn': '📲 Reservar mi sesión',

    // Testimonials
    'reviews.label': 'Opiniones de Clientes',
    'reviews.title': 'Lo que dicen nuestros clientes',
    'reviews.desc': 'La satisfacción y discreción de nuestros clientes son nuestras máximas prioridades. Descubra su experiencia en SPA RELAX ISTANBUL.',
    'reviews.r1.name': 'Youssef El Amrani',
    'reviews.r1.role': 'Empresario, Tetuán',
    'reviews.r1.quote': 'Sinceramente, el mejor centro de masajes para hombres en Tetuán. El lugar es lujoso, limpio y extremadamente discreto. El masaje Deep Tissue me liberó por completo del dolor muscular.',
    'reviews.r2.name': 'Amine B.',
    'reviews.r2.role': 'Profesional Independiente, Tánger',
    'reviews.r2.quote': '¡Servicio de 5 estrellas! La acogida es respetuosa y profesional. Todo está diseñado para que te sientas cómodo. La higiene es impecable.',
    'reviews.r3.name': 'Rachid Tetouani',
    'reviews.r3.role': 'Cliente Regular, Tetuán',
    'reviews.r3.quote': '¡Un verdadero masaje terapéutico profesional! Nada que ver con otros lugares básicos. Los aceites utilizados son de muy alta calidad. Altamente recomendado.',

    // FAQ
    'faq.label': 'Preguntas Frecuentes',
    'faq.title': '¿Tiene preguntas? Tenemos las respuestas',
    'faq.desc': 'Encuentre todas las respuestas a las preguntas más comunes sobre nuestros masajes, políticas de reserva y centro en Tetuán.',
    'faq.q1': '¿Los masajes son mixtos o solo para hombres?',
    'faq.a1': 'SPA RELAX ISTANBUL es un entorno exclusivamente masculino (men-only). Los masajes se realizan en un entorno totalmente privado para garantizar la mayor comodidad, respeto y relajación.',
    'faq.q2': '¿Ofrecen servicios de hammam o exfoliación?',
    'faq.a2': 'No, nuestro centro está especializado exclusivamente en masajes terapéuticos profesionales de alta calidad. No ofrecemos servicios de hammam tradicional.',
    'faq.q3': '¿Es obligatorio reservar con antelación?',
    'faq.a3': 'Sí, para garantizar su cabina privada y disponibilidad inmediata sin tiempos de espera, todas las sesiones de masaje se realizan estrictamente con reserva previa.',
    'faq.q4': '¿Qué tipo de aceites de masaje utilizan?',
    'faq.a4': 'Utilizamos exclusivamente aceites de almendras dulces, aceites de coco orgánicos y aceites esenciales premium seleccionados por sus propiedades calmantes y reparadoras.',
    'faq.q5': '¿Dónde se encuentra exactamente el spa en Tetuán?',
    'faq.a5': 'Nuestro centro de bienestar está ubicado en la Avenida Kabul, Tiknia 93030, Tetuán. Un lugar tranquilo, elegante y muy accesible con opciones de estacionamiento cercanas.',

    // Location
    'contact.label': 'Dónde Encontrarnos',
    'contact.title': 'Nuestro Centro en Tetuán',
    'contact.desc': 'Idealmente ubicado en un barrio tranquilo y muy accesible en Tetuán. Venga a recargar energías en nuestro espacio de bienestar para hombres.',
    'contact.info': 'INFORMACIÓN DE CONTACTO',
    'contact.address.label': 'Dirección',
    'contact.address.val': 'SPA RELAX ISTANBUL, Avenida Kabul, Tiknia 93030, Tetuán, Marruecos',
    'contact.phone.label': 'WhatsApp y Teléfono',
    'contact.phone.val': '+212779403213',
    'contact.hours.label': 'Horario de Apertura',
    'contact.hours.val': 'Todos los días: de 10:30 a 23:30',
    'contact.hours.note': '* Estrictamente bajo cita previa o reserva.',
    'contact.btn.wa': '📲 Reservar en WhatsApp',
    'contact.btn.maps': '🗺 Direcciones en Google Maps',

    // Footer
    'footer.slogan': 'ESTAMBUL · TETUÁN',
    'footer.desc': 'Centro de masajes de lujo para hombres en Tetuán. Un oasis exclusivo donde la relajación absoluta se une al refinamiento otomano y la excelencia terapéutica.',
    'footer.spec.title': 'Nuestras Especialidades',
    'footer.spec.s1': 'Masaje Relajante Profesional',
    'footer.spec.s2': 'Masaje Deep Tissue Antiestrés',
    'footer.spec.s3': 'Terapia de Piedras Volcánicas Calientes',
    'footer.spec.s4': 'Masaje de Cabeza y Reflexología',
    'footer.spec.s5': 'Aromaterapia Orgánica Bio',
    'footer.spec.s6': 'Rituales Customizados VIP para Hombres',
    'footer.contact.title': 'Contacto Rápido',
    'footer.btn.live': '📲 Chat en Vivo por WhatsApp',
    'footer.copy': 'Todos los derechos reservados. Tratamientos de bienestar estrictamente profesionales y solo para hombres.',
    'footer.legal': 'Aviso Legal',
    'footer.privacy': 'Política de Privacidad',

    // Chatbot
    'chat.notify': '¡Hola! ¿Alguna pregunta?',
    'chat.status': 'En línea ahora',
    'chat.greet1': '¡Marhaban! Bienvenido a SPA RELAX ISTANBUL en Tetuán. 🇲🇦🇹🇷',
    'chat.greet2': 'Soy Youssef, su asesor de bienestar. ¿Cómo puedo ayudarle hoy?',
    'chat.hours': 'Gerente del Spa · 10:30 - 23:30',
    'chat.opt1': '💆‍♂️ Reservar una sesión de masaje',
    'chat.opt2': '💰 Preguntar sobre precios y ofertas',
    'chat.opt3': '📍 Cómo llegar al centro',
    'chat.opt4': '🤔 Preguntar sobre tipos de masajes',
    'chat.placeholder': 'Escriba su mensaje...',
  },
  it: {
    // Navbar
    'nav.home': 'Home',
    'nav.services': 'Trattamenti',
    'nav.gallery': 'Galleria',
    'nav.reviews': 'Recensioni',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contatti',
    'nav.book': 'Prenota',

    // Hero
    'hero.badge': 'MASSAGGIO MASCHILE DI LUSSO PREMIUM · TETOUAN',
    'hero.title1': 'L\'arte suprema del ',
    'hero.titleItalic': 'rilassamento',
    'hero.title2': ' per uomini',
    'hero.desc1': 'Libera la mente e rivitalizza il corpo nel cuore di Tetouan. ',
    'hero.descBold': 'SPA RELAX ISTANBUL',
    'hero.desc2': ' ti offre massaggi eccezionali in un ambiente privato, elegante ed esclusivamente maschile.',
    'hero.descItalic': ' Massaggio 100% professionale, terapeutico e antistress.',
    'hero.trust.masseur': 'Massaggiatori Esperti',
    'hero.trust.frame': 'Ambiente Privato e Discreto',
    'hero.trust.hygiene': 'Igiene Rigorosa',
    'hero.btn.wa': 'PRENOTA SU WHATSAPP',
    'hero.btn.services': 'I NOSTRI SERVIZI',

    // Benefits
    'benefits.label': 'Perché Sceglierci',
    'benefits.title': 'L\'eccellenza nel benessere maschile',
    'benefits.desc': 'Ridefiniamo gli standard del massaggio maschile a Tetouan grazie a terapisti altamente certificati e trattamenti di alta gamma.',
    'benefits.b1.title': 'Igiene Assoluta',
    'benefits.b1.desc': 'Cabine completamente pulite e igienizzate dopo ogni cliente; lenzuola e asciugamani monouso.',
    'benefits.b2.title': 'Discrezione Totale',
    'benefits.b2.desc': 'Ambiente caldo e altamente discreto che rispetta pienamente la tua privacy. Ingresso e uscita sicuri.',
    'benefits.b3.title': 'Terapisti Certificati',
    'benefits.b3.desc': 'Un team professionale che domina le migliori tecniche di rilassamento orientali e occidentali.',
    'benefits.b4.title': 'Oli Biologici Premium',
    'benefits.b4.desc': 'Uso esclusivo di oli essenziali biologici premium adatti al tuo tipo di pelle.',

    // Services
    'services.label': 'I Nostri Rituali di Cura',
    'services.title': 'Massaggi Eccezionali e Terapie',
    'services.desc': 'Ogni massaggio è eseguito da un esperto certificato, utilizzando oli per aromaterapia adatti alle tue tensioni fisiche.',
    'services.rec': 'Consigliato',
    'services.min': 'Min',
    'services.btn': 'Prenota su WhatsApp',
    'services.s1.title': 'Massaggio Rilassante Tradizionale',
    'services.s1.desc': 'Un massaggio fluido e avvolgente su tutto il corpo. Ideale per eliminare la fatica quotidiana, rilasciare le tensioni muscolari e ripristinare la totale armonia.',
    'services.s2.title': 'Massaggio Deep Tissue (Antistress)',
    'services.s2.desc': 'Un massaggio profondo mirato agli strati muscolari e alla fascia. Consigliato per sportivi, professionisti attivi e tensioni alla schiena.',
    'services.s3.title': 'Massaggio Orientale con Pietre Calde',
    'services.s3.desc': 'Il mix perfetto di pietre vulcaniche calde e pressione rilassante. Favorisce un profondo rilassamento muscolare e migliora la circolazione.',
    'services.s4.title': 'Rituale VIP - SPA RELAX ISTANBUL',
    'services.s4.desc': 'La nostra esperienza di rilassamento definitiva. Un massaggio su misura che combina oli essenziali biologici, massaggio rilassante alla testa e riflessologia.',

    // Gallery
    'gallery.label': 'Visita Guidata',
    'gallery.title': 'Galleria del Nostro Centro',
    'gallery.desc': 'Immergiti nell\'atmosfera raffinata della nostra spa a Tetouan. Arredamento curato, luci soffuse e igiene rigorosa.',
    'gallery.c1': 'Spazio Relax',
    'gallery.c2': 'Ingredienti e Cura',
    'gallery.c3': 'Atmosfera',
    'gallery.c4': 'Cura Maschile',
    'gallery.c5': 'Ambiente Privato',
    'gallery.c6': 'Reception',
    'gallery.t1': 'Cabina Privata Premium',
    'gallery.t2': 'Rilassamento Totale',
    'gallery.t3': 'Ambiente Terapeutico',
    'gallery.t4': 'Pedicure e Cura dei Piedi',
    'gallery.t5': 'Atmosfera Calda e Soffusa',
    'gallery.t6': 'Reception VIP',
    'gallery.cta.title': 'Pronto per un momento di relax assoluto?',
    'gallery.cta.desc': 'Prenota ora il tuo appuntamento su WhatsApp. Programmazione rapida e totalmente discreta.',
    'gallery.cta.btn': '📲 Prenota la mia sessione',

    // Testimonials
    'reviews.label': 'Recensioni dei Clienti',
    'reviews.title': 'Cosa dicono i nostri clienti',
    'reviews.desc': 'La soddisfazione e la discrezione dei nostri clienti sono le nostre massime priorità. Scopri la loro esperienza presso SPA RELAX ISTANBUL.',
    'reviews.r1.name': 'Youssef El Amrani',
    'reviews.r1.role': 'Imprenditore, Tetouan',
    'reviews.r1.quote': 'Onestamente, il miglior centro massaggi per uomini a Tetouan. Il posto è lussuoso, pulito ed estremamente discreto. Il massaggio Deep Tissue mi ha liberato completamente dal dolore muscolare.',
    'reviews.r2.name': 'Amine B.',
    'reviews.r2.role': 'Libero Professionista, Tangeri',
    'reviews.r2.quote': 'Servizio da 5 stelle! L\'accoglienza è rispettosa e professionale. Tutto è progettato per farti sentire a tuo agio. L\'igiene è impeccabile.',
    'reviews.r3.name': 'Rachid Tetouani',
    'reviews.r3.role': 'Cliente Regolare, Tetouan',
    'reviews.r3.quote': 'Un vero massaggio terapeutico professionale! Niente a che vedere con altri posti base. Gli oli utilizzati sono di altissima qualità. Altamente raccomandato.',

    // FAQ
    'faq.label': 'Domande Frequenti',
    'faq.title': 'Hai domande? Abbiamo le risposte',
    'faq.desc': 'Trova tutte le risposte alle domande più comuni sui nostri massaggi, sulle politiche di prenotazione e sul nostro centro a Tetouan.',
    'faq.q1': 'I massaggi sono misti o solo per uomini?',
    'faq.a1': 'SPA RELAX ISTANBUL è un ambiente esclusivamente maschile (men-only). I massaggi vengono eseguiti in un ambiente totalmente privato per garantire il massimo comfort, rispetto e rilassamento.',
    'faq.q2': 'Offrite servizi di hammam o scrub?',
    'faq.a2': 'No, il nostro centro è specializzato esclusivamente in massaggi terapeutici professionali di alta qualità. Non offriamo servizi di hammam tradizionale.',
    'faq.q3': 'È obbligatorio prenotare in anticipo?',
    'faq.a3': 'Sì, per garantire la tua cabina privata e la disponibilità immediata senza tempi di attesa, tutte le sessioni di massaggio vengono effettuate rigorosamente previa prenotazione.',
    'faq.q4': 'Che tipo di oli da massaggio utilizzate?',
    'faq.a4': 'Utilizziamo esclusivamente oli di mandorle dolci, oli di cocco biologici e oli essenziali premium selezionati per le loro proprietà lenitive e riparatrici.',
    'faq.q5': 'Dove si trova esattamente la spa a Tetouan?',
    'faq.a5': 'Il nostro centro benessere si trova in Avenue Kabul, Tiknia 93030, Tetouan. Un luogo tranquillo, elegante e molto accessibile con opzioni di parcheggio nelle vicinanze.',

    // Location
    'contact.label': 'Dove Trovarci',
    'contact.title': 'Il Nostro Centro a Tetouan',
    'contact.desc': 'Situato in una zona tranquilla e facilmente accessibile a Tetouan. Vieni a ricaricarti nel nostro spazio benessere per soli uomini.',
    'contact.info': 'INFORMAZIONI DI CONTATTO',
    'contact.address.label': 'Indirizzo',
    'contact.address.val': 'SPA RELAX ISTANBUL, Avenue Kabul, Tiknia 93030, Tetouan, Marocco',
    'contact.phone.label': 'WhatsApp e Telefono',
    'contact.phone.val': '+212779403213',
    'contact.hours.label': 'Orari di Apertura',
    'contact.hours.val': 'Tutti i giorni: dalle 10:30 alle 23:30',
    'contact.hours.note': '* Rigorosamente su appuntamento o prenotazione previa.',
    'contact.btn.wa': '📲 Prenota su WhatsApp',
    'contact.btn.maps': '🗺 Indicazioni su Google Maps',

    // Footer
    'footer.slogan': 'ISTANBUL · TETOUAN',
    'footer.desc': 'Centro massaggi di lusso per uomini a Tetouan. Un\'oasi esclusiva dove il rilassamento assoluto incontra la raffinatezza ottomana e l\'eccellenza terapeutica.',
    'footer.spec.title': 'Le Nostre Specialità',
    'footer.spec.s1': 'Massaggio Rilassante Professionale',
    'footer.spec.s2': 'Massaggio Deep Tissue Antistress',
    'footer.spec.s3': 'Terapia con Pietre Vulcaniche Calde',
    'footer.spec.s4': 'Massaggio alla Testa e Riflessologia',
    'footer.spec.s5': 'Aromaterapia Biologica Bio',
    'footer.spec.s6': 'Rituali VIP Personalizzati per Uomini',
    'footer.contact.title': 'Contatto Rapido',
    'footer.btn.live': '📲 Chat live su WhatsApp',
    'footer.copy': 'Tutti i diritti riservati. Trattamenti di benessere rigorosamente professionali e solo per uomini.',
    'footer.legal': 'Note Legali',
    'footer.privacy': 'Informativa sulla Privacy',

    // Chatbot
    'chat.notify': 'Ciao! Hai domande?',
    'chat.status': 'Online ora',
    'chat.greet1': 'Marhaban! Benvenuto a SPA RELAX ISTANBUL a Tetouan. 🇲🇦🇹🇷',
    'chat.greet2': 'Sono Youssef, il tuo consulente di benessere. Come posso aiutarti oggi?',
    'chat.hours': 'Responsabile Spa · 10:30 - 23:30',
    'chat.opt1': '💆‍♂️ Prenota una sessione di massaggio',
    'chat.opt2': '💰 Chiedi informazioni su prezzi e offerte',
    'chat.opt3': '📍 Indicazioni per raggiungere il centro',
    'chat.opt4': '🤔 Chiedi informazioni sui tipi di massaggio',
    'chat.placeholder': 'Scrivi il tuo messaggio...',
  },
  tr: {
    // Navbar
    'nav.home': 'Ana Sayfa',
    'nav.services': 'Bakımlar',
    'nav.gallery': 'Galeri',
    'nav.reviews': 'Yorumlar',
    'nav.faq': 'SSS',
    'nav.contact': 'İletişim',
    'nav.book': 'Rezervasyon Yap',

    // Hero
    'hero.badge': 'PREMİUM LÜKS ERKEKLERE ÖZEL MASAJ · TETUAN',
    'hero.title1': 'Erkekler için ',
    'hero.titleItalic': 'rahatlamanın',
    'hero.title2': ' en üstün sanatı',
    'hero.desc1': 'Tetuan\'ın kalbinde zihninizi serbest bırakın ve vücudunuzu canlandırın. ',
    'hero.descBold': 'SPA RELAX ISTANBUL',
    'hero.desc2': ' size özel, şık ve yalnızca erkeklere özel bir ortamda olağanüstü masajlar sunar.',
    'hero.descItalic': ' %100 profesyonel, terapötik ve stres önleyici masaj.',
    'hero.trust.masseur': 'Uzman Masörler',
    'hero.trust.frame': 'Gizli Özel Ortam',
    'hero.trust.hygiene': 'Sıkı Hijyen Standartları',
    'hero.btn.wa': 'WHATSAPP İLE REZERVASYON YAP',
    'hero.btn.services': 'HİZMETLERİMİZ',

    // Benefits
    'benefits.label': 'Neden Biz',
    'benefits.title': 'Erkek Sağlığında Mükemmellik',
    'benefits.desc': 'Sertifikalı terapistlerimiz ve üst düzey bakımlarımız sayesinde Tetuan\'da erkek masajı standartlarını yeniden tanımlıyoruz.',
    'benefits.b1.title': 'Mutlak Hijyen',
    'benefits.b1.desc': 'Kabinler her müşteriden sonra tamamen temizlenir ve dezenfekte edilir; tek kullanımlık çarşaf ve havlular kullanılır.',
    'benefits.b2.title': 'Tam Gizlilik',
    'benefits.b2.desc': 'Gizliliğinize tamamen saygı duyan sıcak ve son derece özel bir ortam. Güvenli giriş ve çıkış.',
    'benefits.b3.title': 'Sertifikalı Terapistler',
    'benefits.b3.desc': 'En iyi Doğu ve Batı rahatlama tekniklerine hakim profesyonel bir ekip.',
    'benefits.b4.title': 'Premium Organik Yağlar',
    'benefits.b4.desc': 'Cilt tipinize uygun olarak seçilen organik, birinci sınıf esansiyel yağların özel kullanımı.',

    // Services
    'services.label': 'Bakım Ritüellerimiz',
    'services.title': 'Olağanüstü Masajlar ve Terapiler',
    'services.desc': 'Her masaj, fiziksel gerginliklerinize göre uyarlanmış özel aromaterapi yağları kullanan sertifikalı bir uzman tarafından gerçekleştirilir.',
    'services.rec': 'Önerilen',
    'services.min': 'Dk',
    'services.btn': 'WhatsApp\'tan Rezervasyon Yap',
    'services.s1.title': 'Geleneksel Rahatlatıcı Masaj',
    'services.s1.desc': 'Tüm vücudu kapsayan akıcı ve sarıcı bir masaj. Günlük yorgunluğu gidermek, kas gerginliğini azaltmak ve tam uyumu geri kazanmak için idealdir.',
    'services.s2.title': 'Derin Doku Masajı (Stres Karşıtı)',
    'services.s2.desc': 'Derin kas katmanlarını ve fasyayı hedef alan derin bir masaj. Sporcular, aktif profesyoneller ve sırt gerginliği olanlar için önerilir.',
    'services.s3.title': 'Sıcak Taşlı Oryantal Masaj',
    'services.s3.desc': 'Sıcak volkanik taşların ve rahatlatıcı basıncın mükemmel karışımı. Derin kas gevşemesini teşvik eder ve kan dolaşımını artırır.',
    'services.s4.title': 'VIP Ritüel - SPA RELAX ISTANBUL',
    'services.s4.desc': 'En üst düzey rahatlama deneyimimiz. Organik esansiyel yağlar, sakinleştirici baş masajı ve refleksolojiyi birleştiren kişiye özel bir masaj.',

    // Gallery
    'gallery.label': 'Rehberli Tur',
    'gallery.title': 'Merkezimizin Galerisi',
    'gallery.desc': 'Tetuan\'daki spamızın rafine atmosferine kendinizi bırakın. Özel dekorasyon, loş ışıklar ve sıkı hijyen.',
    'gallery.c1': 'Rahatlama Alanı',
    'gallery.c2': 'Malzemeler ve Bakım',
    'gallery.c3': 'Atmosfer',
    'gallery.c4': 'Erkek Bakımı',
    'gallery.c5': 'Özel Ortam',
    'gallery.c6': 'Resepsiyon',
    'gallery.t1': 'Premium Özel Kabin',
    'gallery.t2': 'Tam Rahatlama',
    'gallery.t3': 'Terapötik Ortam',
    'gallery.t4': 'Pedikür ve Ayak Bakımı',
    'gallery.t5': 'Loş ve Sıcak Atmosfer',
    'gallery.t6': 'VIP Karşılama Lobisi',
    'gallery.cta.title': 'Mutlak bir rahatlama anına hazır mısınız?',
    'gallery.cta.desc': 'WhatsApp üzerinden hemen rezervasyon yapın. Hızlı ve tamamen gizli planlama.',
    'gallery.cta.btn': '📲 Seansımı Ayarla',

    // Testimonials
    'reviews.label': 'Müşteri Yorumları',
    'reviews.title': 'Müşterilerimiz bizim için ne diyor?',
    'reviews.desc': 'Müşterilerimizin memnuniyeti ve gizliliği en büyük önceliğimizdir. SPA RELAX ISTANBUL deneyimlerini keşfedin.',
    'reviews.r1.name': 'Youssef El Amrani',
    'reviews.r1.role': 'İşletme Sahibi, Tetuan',
    'reviews.r1.quote': 'Dürüst olmak gerekirse, Tetuan\'daki erkekler için en iyi masaj merkezi. Mekan lüks, temiz ve son derece gizli. Derin doku masajı beni kas ağrılarımdan tamamen kurtardı.',
    'reviews.r2.name': 'Amine B.',
    'reviews.r2.role': 'Serbest Meslek Sahibi, Tanca',
    'reviews.r2.quote': '5 yıldızlı hizmet! Karşılama son derece saygılı ve profesyonel. Kendinizi rahat hissetmeniz için her şey tasarlanmış. Hijyen kusursuz.',
    'reviews.r3.name': 'Rachid Tetouani',
    'reviews.r3.role': 'Düzenli Müşteri, Tetuan',
    'reviews.r3.quote': 'Gerçek bir profesyonel terapötik masaj! Diğer basit yerlerle hiç alakası yok. Kullanılan yağlar çok kaliteli. Kesinlikle tavsiye ederim.',

    // FAQ
    'faq.label': 'Sıkça Sorulan Sorular',
    'faq.title': 'Sorularınız mı var? Cevaplarımız hazır',
    'faq.desc': 'Masajlarımız, rezervasyon politikalarımız ve Tetuan\'daki merkezimiz hakkında en sık sorulan soruların tüm cevaplarını bulun.',
    'faq.q1': 'Masajlar karma mı yoksa sadece erkeklere özel mi?',
    'faq.a1': 'SPA RELAX ISTANBUL sadece erkeklere özel bir ortamdır. Masajlar, en yüksek konfor, saygı ve rahatlamayı sağlamak için tamamen özel bir kabinde gerçekleştirilir.',
    'faq.q2': 'Hammam veya kese hizmeti sunuyor musunuz?',
    'faq.a2': 'Hayır, merkezimiz sadece profesyonel, yüksek kaliteli terapötik masajlar konusunda uzmanlaşmıştır. Geleneksel hamam hizmeti sunmamaktayız.',
    'faq.q3': 'Önceden rezervasyon yaptırmak zorunlu mu?',
    'faq.a3': 'Evet, özel kabininizi ve beklemeden seansınızı garanti etmek için tüm masaj seansları yalnızca önceden yapılan rezervasyonlarla gerçekleştirilir.',
    'faq.q4': 'Ne tür masaj yağları kullanıyorsunuz?',
    'faq.a4': 'Yalnızca yatıştırıcı ve yenileyici özellikleri için seçilmiş tatlı badem yağları, organik hindistan cevizi yağları ve birinci sınıf esansiyel yağlar kullanıyoruz.',
    'faq.q5': 'Spa Tetuan\'da tam olarak nerede bulunuyor?',
    'faq.a5': 'Sağlıklı yaşam merkezimiz Kabil Caddesi, Tiknia 93030, Tetuan adresinde yer almaktadır. Yakınlarda park seçenekleri bulunan sakin, şık ve son derece erişilebilir bir konumdur.',

    // Location
    'contact.label': 'Neredeyiz?',
    'contact.title': 'Tetuan\'daki Merkezimiz',
    'contact.desc': 'Tetuan\'da sakin ve son derece erişilebilir bir mahallede ideal bir konumda yer almaktadır. Erkeklere özel merkezimizde yenilenmeye gelin.',
    'contact.info': 'İLETİŞİM BİLGİLERİ',
    'contact.address.label': 'Adres',
    'contact.address.val': 'SPA RELAX ISTANBUL, Kabil Caddesi, Tiknia 93030, Tetuan, Fas',
    'contact.phone.label': 'WhatsApp & Telefon',
    'contact.phone.val': '+212779403213',
    'contact.hours.label': 'Açılış Saatleri',
    'contact.hours.val': 'Her gün: 10:30 - 23:30 saatleri arasında',
    'contact.hours.note': '* Yalnızca önceden yapılan randevu veya rezervasyon ile.',
    'contact.btn.wa': '📲 WhatsApp\'tan Rezervasyon Yap',
    'contact.btn.maps': '🗺 Google Haritalar Yol Tarifi',

    // Footer
    'footer.slogan': 'İSTANBUL · TETUAN',
    'footer.desc': 'Tetuan\'da erkekler için lüks masaj merkezi. Mutlak rahatlamanın Osmanlı zarafeti ve terapötik mükemmellikle buluştuğu özel bir sığınak.',
    'footer.spec.title': 'Uzmanlık Alanlarımız',
    'footer.spec.s1': 'Profesyonel Rahatlatıcı Masaj',
    'footer.spec.s2': 'Stres Karşıtı Derin Doku Masajı',
    'footer.spec.s3': 'Volkanik Sıcak Taş Terapisi',
    'footer.spec.s4': 'Baş Masajı & Refleksoloji',
    'footer.spec.s5': 'Biyo Organik Aromaterapi',
    'footer.spec.s6': 'VIP Özel Erkek Ritüelleri',
    'footer.contact.title': 'Hızlı İletişim',
    'footer.btn.live': '📲 WhatsApp Canlı Destek',
    'footer.copy': 'Tüm hakları saklıdır. Sadece profesyonel ve erkeklere özel bakımlar.',
    'footer.legal': 'Yasal Uyarı',
    'footer.privacy': 'Gizlilik Politikası',

    // Chatbot
    'chat.notify': 'Merhaba! Sorunuz mu var?',
    'chat.status': 'Şu an çevrimiçi',
    'chat.greet1': 'Marhaban! Tetuan\'daki SPA RELAX ISTANBUL\'a hoş geldiniz. 🇲🇦🇹🇷',
    'chat.greet2': 'Ben sağlıklı yaşam danışmanınız Youssef. Bugün size nasıl yardımcı olabilirim?',
    'chat.hours': 'Spa Müdürü · 10:30 - 23:30',
    'chat.opt1': '💆‍♂️ Masaj seansı rezervasyonu yap',
    'chat.opt2': '💰 Fiyatlar ve teklifler hakkında bilgi al',
    'chat.opt3': '📍 Merkezin konumunu öğren',
    'chat.opt4': '🤔 Masaj türleri hakkında soru sor',
    'chat.placeholder': 'Escreva sua mensagem...',
  },
  pt: {
    // Navbar
    'nav.home': 'Início',
    'nav.services': 'Serviços',
    'nav.gallery': 'Galeria',
    'nav.reviews': 'Avaliações',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contato',
    'nav.book': 'Reservar',

    // Hero
    'hero.badge': 'MASSAGEM PREMIUM PARA HOMENS · TETUAN',
    'hero.title1': 'A arte suprema da ',
    'hero.titleItalic': 'relaxamento',
    'hero.title2': ' para homens',
    'hero.desc1': 'Libere sua mente e revitalize e seu corpo no centro de Tetuán. ',
    'hero.descBold': 'SPA RELAX ISTANBUL',
    'hero.desc2': ' oferece massagens excepcionais em um ambiente privado, elegante e exclusivamente masculino.',
    'hero.descItalic': ' Massagem 100% profissional, terapêutica e anti-stress.',
    'hero.trust.masseur': 'Massagistas Especialistas',
    'hero.trust.frame': 'Ambiente Privado Discreto',
    'hero.trust.hygiene': 'Higiene Rigorosa',
    'hero.btn.wa': 'RESERVAR PELO WHATSAPP',
    'hero.btn.services': 'NOSSOS SERVIÇOS',

    // Benefits
    'benefits.label': 'Por Que Escolher Nosso Centro',
    'benefits.title': 'Excelência no Bem-Estar Masculino',
    'benefits.desc': 'Redefinimos os padrões da massagem para homens em Tetuán graças a terapeutas altamente certificados e tratamentos de alta gama.',
    'benefits.b1.title': 'Higiene Absoluta',
    'benefits.b1.desc': 'Cabines limpas e desinfetadas após cada cliente; lençóis e toalhas de uso único.',
    'benefits.b2.title': 'Discreção Total',
    'benefits.b2.desc': 'Ambiente quente e altamente discreto que respeita plenamente sua privacidade. Entrada e saída seguras.',
    'benefits.b3.title': 'Terapeutas Certificados',
    'benefits.b3.desc': 'Uma equipe profissional dominando as melhores técnicas orientais e ocidentais de relaxamento.',
    'benefits.b4.title': 'Óleos Orgânicos Premium',
    'benefits.b4.desc': 'Uso exclusivo de óleos essenciais orgânicos premium adaptados ao seu tipo de pele.',

    // Services
    'services.label': 'Nossos Rituais de Cuidado',
    'services.title': 'Massagens Excepcionais e Terapias',
    'services.desc': 'Cada massagem é realizada por um especialista certificado, usando óleos de aromaterapia adaptados às suas tensões físicas.',
    'services.rec': 'Recomendado',
    'services.min': 'Min',
    'services.btn': 'Reservar no WhatsApp',
    'services.s1.title': 'Massagem Relaxante Tradicional',
    'services.s1.desc': 'Uma massagem fluida e envolvente pelo corpo inteiro. Ideal para eliminar a fadiga diária, liberar tensões musculares e restaurar a harmonia total.',
    'services.s2.title': 'Massagem Deep Tissue (Anti-Stress)',
    'services.s2.desc': 'Uma massagem profunda visando camadas musculares e fascia. Recomendada para atletas, profissionais ativos e tensões na espinha.',
    'services.s3.title': 'Massagem Oriental com Pedras Quentes',
    'services.s3.desc': 'A combinação perfeita de pedras vulcânicas quentes e pressão relaxante. Promove uma relaxamento muscular profundo e melhora a circulação.',
    'services.s4.title': 'Ritual VIP - SPA RELAX ISTANBUL',
    'services.s4.desc': 'Nossa experiência de relaxamento definitiva. Uma massagem personalizada combinando óleos essenciais orgânicos, massagem de cabeça relaxante e reflexologia.',

    // Gallery
    'gallery.label': 'Visita Guiada',
    'gallery.title': 'Galeria do Nosso Centro',
    'gallery.desc': 'Imersa-se na atmosfera refinada do nosso spa em Tetuán. Decoração cuidada, luzes suaves e higiene rigorosa.',
    'gallery.c1': 'Espaço Relax',
    'gallery.c2': 'Ingredientes e Cuidados',
    'gallery.c3': 'Ambiente',
    'gallery.c4': 'Cuidados Masculinos',
    'gallery.c5': 'Ambiente Privado',
    'gallery.c6': 'Recepção',
    'gallery.t1': 'Cabine Privada Premium',
    'gallery.t2': 'Relaxamento Total',
    'gallery.t3': 'Ambiente Terapêutico',
    'gallery.t4': 'Pedicure e Cuidados dos Pés',
    'gallery.t5': 'Ambiente Quente e Suave',
    'gallery.t6': 'Recepção VIP',
    'gallery.cta.title': 'Pronto para um momento de relaxamento absoluto?',
    'gallery.cta.desc': 'Reserve sua sessão agora no WhatsApp. Agendamento rápido e totalmente discreto.',
    'gallery.cta.btn': '📲 Reserve minha sessão',

    // Testimonials
    'reviews.label': 'Avaliações de Clientes',
    'reviews.title': 'O que nossos clientes dizem de nós',
    'reviews.desc': 'A satisfação e discreção de nossos clientes são nossas maiores prioridades. Descubra suas experiências no SPA RELAX ISTANBUL.',
    'reviews.r1.name': 'Youssef El Amrani',
    'reviews.r1.role': 'Empresário, Tetuán',
    'reviews.r1.quote': 'Honestamente, o melhor centro de massagem para homens em Tetuán. O local é luxuoso, limpo e extremamente discreto. A massagem Deep Tissue me liberou completamente da dor muscular.',
    'reviews.r2.name': 'Amine B.',
    'reviews.r2.role': 'Profissional Autônomo, Tânger',
    'reviews.r2.quote': 'Serviço de 5 estrelas! O atendimento é respeitoso e profissional. Tudo é feito para você se sentir à vontade. A higiene é impecável.',
    'reviews.r3.name': 'Rachid Tetouani',
    'reviews.r3.role': 'Cliente Regular, Tetuán',
    'reviews.r3.quote': 'Uma verdadeira massagem terapêutica profissional! Diferente de outros lugares básicos. Os óleos usados são de muita qualidade. Altamente recomendado.',

    // FAQ
    'faq.label': 'Perguntas Frequentes',
    'faq.title': 'Tem dúvidas? Temos as respostas',
    'faq.desc': 'Encontre todas as respostas às perguntas mais comuns sobre nossas massagens, políticas de reserva e centro em Tetuán.',
    'faq.q1': 'As massagens são mistas ou apenas para homens?',
    'faq.a1': 'SPA RELAX ISTANBUL é um ambiente exclusivamente masculino. As massagens são feitas em um ambiente totalmente privado para garantir o máximo conforto, respeito e relaxamento.',
    'faq.q2': 'Vocês oferecem serviços de hammam ou esfoliação?',
    'faq.a2': 'Não, nosso centro é especializado exclusivamente em massagens terapêuticas profissionais de alta qualidade. Não oferecemos serviços de hammam tradicional.',
    'faq.q3': 'É obrigatório reservar com antecedência?',
    'faq.a3': 'Sim, para garantir sua cabine privada e disponibilidade imediata sem tempo de espera, todas as sessões de massagem são estritamente por reserva prévia.',
    'faq.q4': 'Que tipo de óleos de massagem vocês usam?',
    'faq.a4': 'Utilizamos exclusivamente óleos de amêndoa doce, óleos de coco orgânicos e óleos essenciais premium selecionados por suas propriedades relaxantes e restauradoras.',
    'faq.q5': 'Onde fica exatamente o spa em Tetuán?',
    'faq.a5': 'Nosso centro de bem-estar está localizado na Avenida Kabul, Tiknia 93030, Tetuán. Um local tranquilo, elegante e facilmente acessível com opções de estacionamento nearby.',

    // Location
    'contact.label': 'Onde Encontrar-Nos',
    'contact.title': 'Nosso Centro em Tetuán',
    'contact.desc': 'Idealmente localizado em um bairro tranquilo e facilmente acessível em Tetuán. Venha renovar sua energia no nosso espaço de bem-estar masculino.',
    'contact.info': 'INFORMAÇÕES DE CONTATO',
    'contact.address.label': 'Endereço',
    'contact.address.val': 'SPA RELAX ISTANBUL, Avenida Kabul, Tiknia 93030, Tetuán, Marrocos',
    'contact.phone.label': 'WhatsApp e Telefone',
    'contact.phone.val': '+212779403213',
    'contact.hours.label': 'Horários de Funcionamento',
    'contact.hours.val': 'Todos os dias: das 10:30 às 23:30',
    'contact.hours.note': '* Estritamente por marcação ou reserva prévia.',
    'contact.btn.wa': '📲 Reservar no WhatsApp',
    'contact.btn.maps': '🗺 Direções no Google Maps',

    // Footer
    'footer.slogan': 'ISTANBUL · TETUAN',
    'footer.desc': 'Centro de massagem de luxo para homens em Tetuán. Um refúgio exclusivo onde o relaxamento absoluto encontra a refinamento otomano e a excelência terapêutica.',
    'footer.spec.title': 'Nossas Especialidades',
    'footer.spec.s1': 'Massagem Relaxante Profissional',
    'footer.spec.s2': 'Massagem Deep Tissue Anti-Stress',
    'footer.spec.s3': 'Terapia com Pedras Volcânicas Quentes',
    'footer.spec.s4': 'Massagem de Cabeça e Reflexologia',
    'footer.spec.s5': 'Aromaterapia Orgânica Bio',
    'footer.spec.s6': 'Rituais VIP Personalizados para Homens',
    'footer.contact.title': 'Contato Rápido',
    'footer.btn.live': '📲 Chat ao Vivo no WhatsApp',
    'footer.copy': 'Todos os direitos reservados. Tratamentos de bem-estar rigorosamente profissionais e apenas para homens.',
    'footer.legal': 'Aviso Legal',
    'footer.privacy': 'Política de Privacidade',

    // Chatbot
    'chat.notify': 'Olá! Alguma dúvida?',
    'chat.status': 'Online agora',
    'chat.greet1': 'Marhaban! Bem-vindo ao SPA RELAX ISTANBUL em Tetuán. 🇲🇦🇹🇷',
    'chat.greet2': 'Sou Youssef, seu consultor de bem-estar. Como posso ajudar você hoje?',
    'chat.hours': 'Gerente do Spa · 10:30 - 23:30',
    'chat.opt1': '💆‍♂️ Reservar uma sessão de massagem',
    'chat.opt2': '💰 Perguntar sobre preços e ofertas',
    'chat.opt3': '📍 Como chegar ao centro',
    'chat.opt4': '🤔 Perguntar sobre tipos de massagens',
    'chat.placeholder': 'Digite sua mensagem...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');

  useEffect(() => {
    // Load language from localStorage if exists
    const stored = localStorage.getItem('spa_relax_lang') as Language;
    if (stored && ['fr', 'ar', 'en', 'es', 'it', 'tr', 'pt'].includes(stored)) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('spa_relax_lang', lang);
  };

  const t = (key: string): string => {
    const dict = translations[language];
    if (dict && dict[key]) {
      return dict[key];
    }
    // Fallback to French if translation is missing
    const fallbackDict = translations['fr'];
    return fallbackDict[key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    // Dynamically update document dir and lang attributes
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      <div style={{ direction: dir }} className={dir === 'rtl' ? 'rtl-layout' : 'ltr-layout'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
